services:
  devcontainer:
    build: ./.devcontainer/Dockerfile.dockerfile
    volumes:
      - ./:/workspaces:cached
    depends_on:
      pgsql:
        condition: service_healthy
        restart: true
    tty: true
    stdin_open: true
    command: bash

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Boogy*Man225
  pgsql:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres-data:
  mysql-data: