; CLI development: report all warnings and deprecations to stderr.
error_reporting = E_ALL
display_errors = stderr
log_errors = On
register_argc_argv = On
date.timezone = UTC
memory_limit = 512M
max_execution_time = 0
